spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://hivkkmrc:AaqspoKm4AUl9LDX2Bq3knf0yk5HXcK8@mahmud.db.elephantsql.com/hivkkmrc
    username: hivkkmrc
    password: AaqspoKm4AUl9LDX2Bq3knf0yk5HXcK8
    max-active: 3
    ddl-auto: update
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080