spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cidaetunqqlb62hvb54g-a.oregon-postgres.render.com:5432/getandpost
    username: postgress
    password: We803xCsTAN7k6g1wyv13VP2mOq6fbiO
    max-active: 3
    ddl-auto: update
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080